#!/bin/bash

R='\033[0;31m'
Y='\033[1;33m'
G='\033[1;32m'
W='\033[0m'
#######################
#      mrrobot1o1     #
#######################


if [ "$1" ];then
	IP=$(host $1 | sed -n '1p' | awk '{print $NF}')
	ASN=$(curl -s http://ipinfo.io/$IP | jq .org | tr -d \" | awk '{print $1}')
	curl -s "https://api.mxtoolbox.com/api/v1/Lookup/ASN/?argument=$ASN&Authorization=$MX_API" | jq '.Information[] | ."CIDR Range"' |tr -d \"
else
	echo -e "${Y}[${R}!${Y}] Usage: ${G}asnips example.com${W}" 
fi


