#!/bin/bash

#######################
#      mrrobot1o1     #
#######################


R='\033[0;31m'
Y='\033[1;33m'
G='\033[1;32m'
W='\033[0m'

display_help() {
    echo -e "${Y}Usage: ${G}asnips -d ${R}example.com${W}" >&2
    echo -e "       ${G}asnips -m ${R}AS394161${W}" >&2
	echo
	echo -e "   ${Y}-d, --domain${W}          ${G}Get IPs using domains"
    echo -e "   ${Y}-m, --manual${W}          ${G}Get IPs using ASN number${W}"
    echo -e "   ${Y}-h, --help${W}            ${G}Help Menu.${W}"
    echo
    exit 1
}


while :
do
    case "$1" in
      -d | --domain)
          if [ $# -ne 2 ]; then
            display_help
            else
            domain="$2"
            IP=$(host $domain | sed -n '1p' | awk '{print $NF}')
            ASN=$(curl -s http://ipinfo.io/$IP | jq .org | tr -d \" | awk '{print $1}')
            curl -s "https://api.mxtoolbox.com/api/v1/Lookup/ASN/?argument=$ASN&Authorization=$MX_API" | jq -r '.Information[] | ."CIDR Range"'
          fi
          shift 2
          ;;
      -m | --manual)
          if [ $# -ne 2 ]; then
            display_help
            else
            ASN="$2"
            curl -s "https://api.mxtoolbox.com/api/v1/Lookup/ASN/?argument=$ASN&Authorization=$MX_API" | jq -r '.Information[] | ."CIDR Range"'
          fi
          shift 2
          ;;
      -h | --help)
          display_help
          exit 0
          ;;
      -*)
          display_help
          exit 1 
          ;;
      *)
          break
          ;;
    esac
done
